### PR TITLE
NO-JIRA Updated mac script to run all services in new tabs instead

### PR DESCRIPTION
**Pull request by adeel718**

### CODE REVIEW

**Review by AmarkumarJagtap — APPROVED** [review]

**Comment by mikeSmith08** [comment]
This is good and works mostly well, I have two things which don't quite work for me. Firstly if you don't have redis started as a service then the web-ui doesn't work, would it be worthwhile adding something for that? Secondly, claimant-service doesn't start for me as I don't have the environment variables setup, what do you do for your environment variables? I always start via IntelliJ so have them setup in those run profiles.

**Comment by adeel718** [comment]
> This is good and works mostly well, I have two things which don't quite work for me. Firstly if you don't have redis started as a service then the web-ui doesn't work, would it be worthwhile adding something for that? Secondly, claimant-service doesn't start for me as I don't have the environment variables setup, what do you do for your environment variables? I always start via IntelliJ so have them setup in those run profiles.

I normally have these set in my .bash_profile. I will have a look at putting somerthing in so that it checks whether redis is running before starting the ui

**Comment by mikeSmith08** [comment]
> > This is good and works mostly well, I have two things which don't quite work for me. Firstly if you don't have redis started as a service then the web-ui doesn't work, would it be worthwhile adding something for that? Secondly, claimant-service doesn't start for me as I don't have the environment variables setup, what do you do for your environment variables? I always start via IntelliJ so have them setup in those run profiles.
> 
> I normally have these set in my .bash_profile. I will have a look at putting somerthing in so that it checks whether redis is running before starting the ui

Ok, so as a minimum, would it be worthwhile checking for these as a part of the script and failing before it attempts to start everything up, or would you prefer to do that in a separate PR?

**Comment by adeel718** [comment]
> > > This is good and works mostly well, I have two things which don't quite work for me. Firstly if you don't have redis started as a service then the web-ui doesn't work, would it be worthwhile adding something for that? Secondly, claimant-service doesn't start for me as I don't have the environment variables setup, what do you do for your environment variables? I always start via IntelliJ so have them setup in those run profiles.
> > 
> > 
> > I normally have these set in my .bash_profile. I will have a look at putting somerthing in so that it checks whether redis is running before starting the ui
> 
> Ok, so as a minimum, would it be worthwhile checking for these as a part of the script and failing before it attempts to start everything up, or would you prefer to do that in a separate PR?

I can do that as a seperate PR, I can check any dpeendencies before starting up the service.

**Review by YetAnotherMatt — APPROVED** [review]
I Don't have a Mac, so my approval doesn't mean much :)

**Review by mikeSmith08 — APPROVED** [review]

**Review by dwybourn — APPROVED** [review]

**Pull request merged**
